Repository zenialexandre/lotus, pull requests merged in 2025-04, with the labels that each got.

#1 Camera 2D implementation + Resources refactoring
  Cargo.lock
  Cargo.toml
  assets/shaders/texture_shader.wgsl
  examples/breakout.rs
  examples/physics_simulation.rs
  examples/pong.rs
  examples/simple_camera.rs
  examples/simple_shapes.rs
  examples/simple_sprite.rs
  src/core/audio/audio_source.rs
  src/core/camera/camera2d.rs
  src/core/ecs/entity.rs
  src/core/ecs/mod.rs
  src/core/ecs/query.rs
  src/core/ecs/resource.rs
  src/core/ecs/world.rs
  src/core/game_loop.rs
  src/core/managers/rendering_manager.rs
  src/core/managers/windowing_manager.rs
  src/core/physics/transform.rs
  src/core/shape.rs
  src/core/texture.rs
  src/core/time/timer.rs
  src/lib.rs
  tests/ecs.rs
Labels: enhancement

#2 aa
  Cargo.lock
  assets/textures/animations/potion_idle.png
  assets/textures/animations/potion_idle_256x256.png
  assets/textures/animations/potion_idle_64x64.png
  assets/textures/animations/potion_sprite_sheet.png
  assets/textures/animations/rotating_potion_sprite_sheet.png
  assets/textures/animations/scarfy.png
  assets/textures/happy_tree_test.png
  assets/textures/icons/lotus_pink_aligned.ico
  assets/textures/lotus_pink_256x256_aligned.png
  examples/breakout.rs
  examples/physics_simulation.rs
  examples/pong.rs
  examples/simple_animation.rs
  examples/simple_camera.rs
  examples/simple_shapes.rs
  examples/simple_sprite.rs
  src/core/ecs/query.rs
  src/core/ecs/world.rs
  src/core/engine.rs
  src/core/game_loop.rs
  src/core/managers/rendering_manager.rs
  src/core/managers/windowing_manager.rs
  src/core/mod.rs
  src/core/physics/transform.rs
  src/core/text.rs
  src/core/texture/mod.rs
  src/core/texture/sprite.rs
  src/core/texture/sprite_sheet.rs
  src/core/texture/texture.rs
  src/core/visibility.rs
  src/lib.rs
  tests/ecs.rs
Labels: documentation, enhancement

#4 fix: gravity without weight and gravity_factor_pixelated scaled correctly
  src/core/ecs/world.rs
Labels: bug
